name: Terraform Apply

on:
  push:
    branches:
      - main  # This runs the action when changes are pushed to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    # Configure Azure Credentials
    - name: 'Set up Azure Credentials'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Run Terraform Plan (Optional but useful for validation)
    - name: Terraform Plan
      run: terraform plan

    # Apply the Terraform Plan
    - name: Terraform Apply
      run: terraform apply -auto-approve
